---
title: "Advance Topics in Single Cell RNA Seq: scMultiome analysis - prepare R environment"
author: "UCD Bioinformatics Core"
output:
    html_document:
      keep_md: TRUE
---


# Install R packages


```{r eval=F, echo=T}
if (!requireNamespace("BiocManager", quietly = TRUE)){
    install.packages("BiocManager")
}

if (!requireNamespace("Seurat", quietly = TRUE)){
    install.packages("Seurat")
}

if (!requireNamespace("Signac", quietly = TRUE)){
    BiocManager::install("Signac")
}

if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}

if (!requireNamespace("SeuratData", quietly = TRUE)){
    devtools::install_github("SeuratData")
}

if (!requireNamespace("SeuratData", quietly = TRUE)){
    devtools::install_github("SeuratData")
}

if (!requireNamespace("AnnotationHub", quietly = TRUE)){
    BiocManager::install("AnnotationHub")
}

if (!requireNamespace("HGNChelper", quietly = TRUE)){
    BiocManager::install("HGNChelper")
}

if (!requireNamespace("kableExtra", quietly = TRUE)){
    install.packages("kableExtra")
}


if (!requireNamespace("pheatmap", quietly = TRUE)){
    install.packages("pheatmap")
}

## for motif analysis
if (!requireNamespace("chromVAR", quietly = TRUE)){
    BiocManager::install("chromVAR")
}

if (!requireNamespace("BSgenome.Hsapiens.UCSC.hg38", quietly = TRUE)){
    BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
}

if (!requireNamespace("JASPAR2020", quietly = TRUE)){
    BiocManager::install("JASPAR2020")
}

if (!requireNamespace("motifmatchr", quietly = TRUE)){
    BiocManager::install("motifmatchr")
}


## for transcription factors analysis
if (!requireNamespace("TFBSTools", quietly = TRUE)){
    BiocManager::install("TFBSTools")
}

```

#### Download Rmd
```{r download_Rmd, eval=FALSE}
download.file("https://raw.githubusercontent.com/ucdavis-bioinformatics-training/2024-June-Advanced-Topics-in-Single-Cell-RNA-Seq-Multiome/main/data_analysis/.Rmd", "02-filtering.Rmd")
```

#### Session information
```{r sessioinfo}
sessionInfo()
```
